In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
new_arr = np.array([[5,1,9,11],[2,4,8,10],[13,3,6,7],[15,14,12,16]])
inverse_arr = np.array([[15,13,2,5],[14,3,4,1],[12,6,8,9],[16,7,10,11]])
new_arr

array([[ 5,  1,  9, 11],
       [ 2,  4,  8, 10],
       [13,  3,  6,  7],
       [15, 14, 12, 16]])

In [25]:
inverse_arr

array([[15, 13,  2,  5],
       [14,  3,  4,  1],
       [12,  6,  8,  9],
       [16,  7, 10, 11]])

In [27]:
# for i in range(0,len(new_arr)):
#     for j in range(0,len(new_arr)):
#         print((i,j),new_arr[i,j])

In [23]:
print("INPUT: \n")
print(new_arr)
new_list = []
new_list_1 = []
for i in range(0,len(new_arr)):
    for j in range(0,len(new_arr)):
        # print((i,j),new_arr[i,j])
        temp = new_arr[i,j]
        new_arr[i,j] = new_arr[j,i]
        new_arr[j,i] = temp
        
    new_list.append(temp)
print("OUTPUT:\n")
print(new_list)

INPUT: 

[[ 5  1  9 11]
 [ 2  4  8 10]
 [13  3  6  7]
 [15 14 12 16]]
OUTPUT:

[11, 10, 7, 16]
